name: Terraform Test Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Check Azure env vars
        run: |
          [ -n "$ARM_CLIENT_ID" ] && echo "ARM_CLIENT_ID is set" || echo "ARM_CLIENT_ID is missing"
          [ -n "$ARM_CLIENT_SECRET" ] && echo "ARM_CLIENT_SECRET is set" || echo "ARM_CLIENT_SECRET is missing"
          [ -n "$ARM_SUBSCRIPTION_ID" ] && echo "ARM_SUBSCRIPTION_ID is set" || echo "ARM_SUBSCRIPTION_ID is missing"
          [ -n "$ARM_TENANT_ID" ] && echo "ARM_TENANT_ID is set" || echo "ARM_TENANT_ID is missing"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
